#!/bin/bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/pip_swift/pip_swift/VersionViewController.swift"
PLIST="$ROOT/pip_swift/pip_swift/Info.plist"
[[ "$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST")" == '1.1.1' ]]
rg -qF 'version: L10n.text("1.1.1（26.10.9）"' "$SOURCE"
rg -qF 'version: L10n.text("1.1.1beta3（26.10.8）"' "$SOURCE"
rg -qF 'version: L10n.text("1.1.1beta2（26.10.7）"' "$SOURCE"
! rg -qF 'makeSection(section: AppChangelogCatalog.version111Beta2, showsAsterisks: true)' "$SOURCE"
rg -qF '优化 上次关闭时间 显示逻辑' "$SOURCE"
rg -qF '本次开放iOS15-27实验' "$SOURCE"
rg -qF '并存切换改为悬浮窗启动成功后1秒' "$SOURCE"
PREVIEW="$(sed -n '/private struct PiPUpgradePreviewState/,/final class LatestChangelogViewController/p' "$SOURCE")"
! rg -q 'CADisplayLink|AVAudio|AVPictureInPicture|startPictureInPicture|Timer\(' <<< "$PREVIEW"
rg -qF 'UIAccessibility.isReduceMotionEnabled' <<< "$PREVIEW"
rg -qF 'UIApplication.willResignActiveNotification' <<< "$PREVIEW"
rg -qF 'NotificationCenter.default.removeObserver(self)' <<< "$PREVIEW"
rg -qF 'playback.stop()' <<< "$PREVIEW"
rg -qF 'LaunchPiPTutorialStage(elapsed: elapsed, showsCoexistence: true)' <<< "$PREVIEW"
rg -qF 'paused: !playback.isRunning' <<< "$PREVIEW"
rg -qF 'finishWorkItem?.cancel()' <<< "$PREVIEW"
rg -qF 'var showsCoexistence: Bool = false' "$ROOT/pip_swift/pip_swift/GlobalRefresh2LaunchCelebration.swift"
rg -qF 'makeSection(section: AppChangelogCatalog.latest, showsAsterisks: true)' "$SOURCE"
rg -qF 'section.items.enumerated().map { index, item in' "$SOURCE"
[[ "$(rg -cF 'index < 3 ? "* \(item)" : item' "$SOURCE")" == 2 ]]
rg -qF 'items.systemLayoutSizeFitting(' "$SOURCE"
rg -qF 'buttons.axis = showsUpgradePreview ? .horizontal : .vertical' "$SOURCE"
! rg -qF 'showsUpgradePreview ? 740' "$SOURCE"
CHANGELOG="$(sed -n '/final class ChangelogViewController:/,/private final class UpdateAvailableViewController:/p' "$SOURCE")"
rg -qF 'make.leading.trailing.equalTo(contentView).inset(24)' <<< "$CHANGELOG"
rg -qF 'make.leading.trailing.equalTo(contentView)' <<< "$CHANGELOG"
rg -qF 'scrollView.contentInsetAdjustmentBehavior = .never' <<< "$CHANGELOG"
! rg -qF 'make.leading.trailing.bottom.equalTo(contentView.safeAreaLayoutGuide)' <<< "$CHANGELOG"
FAQ="$(sed -n '/private final class FAQViewController:/,$p' "$SOURCE")"
rg -qF 'make.leading.trailing.equalTo(contentView).inset(24)' <<< "$FAQ"
rg -qF 'scrollView.contentInsetAdjustmentBehavior = .never' <<< "$FAQ"
! rg -qF 'make.leading.trailing.bottom.equalTo(contentView.safeAreaLayoutGuide)' <<< "$FAQ"
! rg -qF 'make.leading.trailing.equalTo(contentView.safeAreaLayoutGuide).inset(24)' "$ROOT/pip_swift/pip_swift/ViewController.swift"
rg -qF 'segment(4.2, 5.2)' "$ROOT/pip_swift/pip_swift/GlobalRefresh2LaunchCelebration.swift"
rg -qF 'segment(7.15, 8.5)' "$ROOT/pip_swift/pip_swift/GlobalRefresh2LaunchCelebration.swift"
rg -qF 'upgradePreview?.stopPreview()' "$SOURCE"
! rg -qF 'items.addArrangedSubview(scope)' "$SOURCE"
TEMP="$(mktemp -d /tmp/pip-upgrade-playback.XXXXXX)"
trap 'rm -rf "$TEMP"' EXIT
printf 'import Foundation\nimport Combine\n' > "$TEMP/playback.swift"
awk '/^private struct PiPUpgradePreviewState/ { copy=1 }
     /^private struct PiPUpgradeTutorialPreview/ { exit }
     copy { sub(/^private /, ""); print }' "$SOURCE" >> "$TEMP/playback.swift"
xcrun swiftc "$TEMP/playback.swift" "$ROOT/tests/upgrade_playback.swift" -o "$TEMP/playback-tests"
"$TEMP/playback-tests"
echo 'PASS: release version, preserved beta history, isolated preview and animation lifecycle'
